sudo: required

# we need docker
services:
  - docker

# what to do before install
before_install:
  - docker build -t muhammadamir/docker_react -f Dockerfile.dev .

# a series of command to run
# coverage is used to return back to command line
# otherwise travis will assume that the test faild
# because our test will not return to command prompt
script:
  - docker run muhammadamir/docker_react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-530948389335"
  bucket_path": "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
